### ISSUE TITLE
Provides/Obsoletes useless or just ignored

### ISSUE THREAD

**Issue by computersalat** [openSUSE/gem2rpm#13]
compare with here:
[rubygem-chef-ruby-lvm](https://build.opensuse.org/package/show/home:computersalat:devel:ruby/rubygem-chef-ruby-lvm)
```
Provides:       rubygem(di-ruby-lvm) = %{version}
Obsoletes:      rubygem(di-ruby-lvm) < %{version}
```

rpm -q --provides /srv/oscbuild/SLE_12-x86_64/home/abuild/rpmbuild/RPMS/x86_64/ruby2.1-rubygem-chef-ruby-lvm-0.4.0-0.x86_64.rpm
```
ruby2.1-rubygem-chef-ruby-lvm = 0.4.0-0
ruby2.1-rubygem-chef-ruby-lvm(x86-64) = 0.4.0-0
rubygem(chef-ruby-lvm) = 0.4.0
rubygem(ruby:2.1.0:chef-ruby-lvm) = 0.4.0
rubygem(ruby:2.1.0:chef-ruby-lvm:0) = 0.4.0
rubygem(ruby:2.1.0:chef-ruby-lvm:0.4) = 0.4.0
rubygem(ruby:2.1.0:chef-ruby-lvm:0.4.0) = 0.4.0
```
the expected `rubygem(di-ruby-lvm) = 0.4.0` is missing.

rpm -q --obsoletes /srv/oscbuild/SLE_12-x86_64/home/abuild/rpmbuild/RPMS/x86_64/ruby2.1-rubygem-chef-ruby-lvm-0.4.0-0.x86_64.rpm
result is empty, so the  expected `rubygem(di-ruby-lvm) < 0.4.0` is missing

**Comment by dcermak** [comment]
I believe that this is an issue in the `%gem_packages` macro, which calls `/usr/bin/gem2rpm.ruby2.6 --local -t /usr/lib/rpm/gem_packages.template chef-ruby-lvm-0.4.0.gem` which in turn outputs all the ruby2.6 subpackages **but** omits the `Provides:` and `Obsoletes:`. 

Note that the `Provides:` and `Obsoletes:` are also omitted, if you add them into the `:preamble:` section in `gem2rpm.yml`.

**Comment by darix** [comment]
```
:main:
  :preamble: |-
     Provides: ...
     Obsoletes: ...
```

That would inject them into each main package per ruby version

a top level :preamble: only affects the unversioned package and is mostly to inject BuildRequires and stuff.

that said ... I am not sure it will uninstall the old di-ruby-lvm package. in any case ... the technology to set them is there.
